version: '3.7'

services:
  mongodb_container:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_USERNAME: beanie
      MONGODB_PASSWORD: beanie
      MONGODB_DATABASE: beanie_db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  beanie:
    depends_on:
      - mongodb_container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: development
    environment:
      - MONGO_HOST=mongodb_container
volumes:
  mongodb_data_container:
