site_name: Documentation
nav:
    - Overview: index.md
    - Setup: setup.md
    - Tutorial:
      - Document: tutorial/document.md
      - Init: tutorial/init.md
      - Create: tutorial/insert.md
      - Find: tutorial/find.md
      - Update: tutorial/update.md
      - Delete: tutorial/delete.md
      - Aggregate: tutorial/aggregate.md
      - Migrations: migrations.md
    - Api reference:
        Document:  api/document.md
        Query: api/queries.md
        Interfaces: api/interfaces.md
        Operators:
            Find: api/operators/find.md
            Update: api/operators/update.md
        Fields: api/fields.md
    - Development: development.md
    - Changelog: changelog.md
theme:
    name: material
    palette:
        primary: white
    logo: assets/logo.svg
    favicon: assets/favicon.png

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
